import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Spotify",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={montserrat.className}>
      <link rel="icon" href="https://open.spotifycdn.com/cdn/images/favicon.0f31d2ea.ico" sizes="any" />
      <body className="bg-zinc-900 text-zinc-50">
        {children}
      </body>
    </html>
  );
}
